version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django_backend
    ports:
      - "4095:8000"  # Map port 4095 (external) to 8000 (internal Django)
    env_file:
      - .env
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      retries: 5