version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django_backend
    ports:
      - "4095:8000"
    environment:
      DJANGO_SECRET_KEY: "DJANGO_SECRET_KEY"
      DEBUG: "False"
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend